### ISSUE TITLE
Create entity-relationship diagram

### ISSUE THREAD

**Issue by PavelEzhkov** [java-practice-spb-2020/epam-ifmo-java-practice-2020-1#3]
Необходимо продумать схему базы данных и нарисовать ее. Можно воспользоваться онлайн сервисом типа https://dbdiagram.io/home .

**Comment by HacksDev** [comment]
https://dbdiagram.io/d/5e3c34ac9e76504e0ef12054

**Comment by Wedds** [comment]
@HacksDev 

1. Кажется, что таблицы `users_info` и `users` можно объединить
2. Таблицу `user_test_questions`, скорее всего, лучше переименовать в `user_test_answers`
3. Какая информация содержится в полe `structure` таблицы `questions`?

**Comment by HacksDev** [comment]
https://dbdiagram.io/d/5e3c34ac9e76504e0ef12054

![Picture Link](https://user-images.githubusercontent.com/57772708/74144110-31158080-4c0d-11ea-8de4-9da150135344.png)

**Comment by Wedds** [comment]
@HacksDev использование типов с плавающей точкой правильно описывает тип данных с точки зрения предметной области, но это плохая практика из-за возможных потерь точности при округлении результатов.  Обычно в случаях, когда хранится что-то дробное (проценты, денежные транзакции), то выбирается точность, определяемая количеством знаков после запятой и все хранится в виде целого числа. Поскольку это тесты, то предлагаю округлять до сотых долей процента

**Comment by HacksDev** [comment]
![Database model](https://user-images.githubusercontent.com/57772708/74509089-be105080-4f11-11ea-8db3-1a31890b9ee0.png)

**Comment by HacksDev** [comment]
![database](https://user-images.githubusercontent.com/57772708/74524583-5d444080-4f30-11ea-8af7-a5d0009935b1.png)
