### ISSUE TITLE
Draw application diagram

### ISSUE THREAD

**Issue by PavelEzhkov** [java-practice-spb-2020/epam-ifmo-java-practice-2020-1#5]

**Comment by HacksDev** [comment]
![sitemap](https://user-images.githubusercontent.com/57772708/74037716-eb1fa900-49cf-11ea-9a4b-5c78520fda76.png)

**Comment by DmitryPuhovsky** [comment]
Лучше удалить http методы т.к. во первых в рамках текущего проекта мы не сможем отправлять запросы с методом delete, а во вторых это не описание API, а лишь схема переходов по старницам.

**Comment by HacksDev** [comment]
![sitemap2](https://user-images.githubusercontent.com/57772708/74468068-40b1f500-4eab-11ea-9c15-f0dd6301670e.png)

**Comment by HacksDev** [comment]
![sitemap7](https://user-images.githubusercontent.com/57772708/74525752-f2483900-4f32-11ea-994a-c886ba2c2ded.png)
