### ISSUE TITLE
Deploy local postgres server

### ISSUE THREAD

**Issue by PavelEzhkov** [java-practice-spb-2020/epam-ifmo-java-practice-2020-1#6]
Install and run a local instance of the postgres server. Use official documentation in Wiki (esp. chapters 18-21).

Acceptance criteria:
1. postgresql-x64-11 windows service is running.
2. A local database is created against which sql commands can be run.

**Comment by Esclide** [comment]
Done

**Comment by HacksDev** [comment]
Done

**Comment by Arahaon** [comment]
Settled

**Comment by Erdandrey** [comment]
Done
