### ISSUE TITLE
Deploy local tomcat server

### ISSUE THREAD

**Issue by PavelEzhkov** [java-practice-spb-2020/epam-ifmo-java-practice-2020-1#7]
Install and run a local instance of the Tomcat web server.

Acceptance criteria:
When entering http://localhost:8080/ in the browser, a Tomcat welcome page is displayed.

**Comment by Esclide** [comment]
Done

**Comment by HacksDev** [comment]
Done

**Comment by Arahaon** [comment]
Deployed

**Comment by Erdandrey** [comment]
Done
